name: WindGIS Deploy Package

on:
  push:
    tags:
      - 'windgis-mapbox-gl-v*.*.*'  # Triggers on tags like windgis-v1.0.0
  workflow_dispatch:  # Allows manual triggering

jobs:
  windgis-prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Extract WindGIS version
        id: version
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            # Extract version from windgis-v1.0.0 -> 1.0.0
            echo "version=${GITHUB_REF#refs/tags/windgis-v}" >> $GITHUB_OUTPUT
          else
            echo "version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT
          fi

  windgis-test-and-build:
    runs-on: ubuntu-latest
    needs: windgis-prepare
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: WindGIS type check
        run: |
          if npm run | grep -q "windgis-typecheck"; then
            npm run windgis-typecheck
          else
            npm run tsc
          fi

      - name: WindGIS lint
        run: |
          if npm run | grep -q "windgis-lint"; then
            npm run windgis-lint
          else
            npm run lint
          fi

      - name: Build WindGIS production
        run: |
          if npm run | grep -q "windgis-build"; then
            npm run windgis-build
          else
            npm run build-prod-min
            npm run build-prod
            npm run build-css
          fi

      - name: Upload WindGIS build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windgis-build-artifacts
          path: |
            dist/
            build/
          retention-days: 1

  windgis-deploy-to-github-packages:
    runs-on: ubuntu-latest
    needs: [windgis-prepare, windgis-test-and-build]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for WindGIS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@Lautec-GIS'  # Replace with your actual org name

      - name: Download WindGIS build artifacts
        uses: actions/download-artifact@v4
        with:
          name: windgis-build-artifacts

      - name: Install dependencies
        run: npm ci --no-audit --no-fund

      - name: Create WindGIS package.json
        run: |
          # Create a separate package.json for WindGIS deployment
          cat > windgis-package.json << EOF
          {
            "name": "windgis/mapbox-gl",
            "version": "${{ needs.windgis-prepare.outputs.version }}",
            "description": "WindGIS version of Mapbox GL JS",
            "main": "dist/mapbox-gl.js",
            "types": "dist/mapbox-gl.d.ts",
            "publishConfig": {
              "registry": "https://npm.pkg.github.com",
              "@Lautec-GIS:registry": "https://npm.pkg.github.com"
            },
            "repository": {
              "type": "git",
              "url": "https://github.com/your-org-name/your-repo-name.git"
            },
            "keywords": ["windgis", "mapbox", "gl", "maps"],
            "license": "BSD-3-Clause",
            "files": [
              "dist/",
              "build/",
              "README.md"
            ]
          }
          EOF

      - name: Publish WindGIS to GitHub Packages
        run: npm publish --registry=https://npm.pkg.github.com windgis-package.json
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  windgis-create-release:
    runs-on: ubuntu-latest
    needs: [windgis-prepare, windgis-deploy-to-github-packages]
    if: startsWith(github.ref, 'refs/tags/windgis-')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download WindGIS build artifacts
        uses: actions/download-artifact@v4
        with:
          name: windgis-build-artifacts

      - name: Create WindGIS release archive
        run: |
          tar -czf windgis-package-${{ needs.windgis-prepare.outputs.version }}.tar.gz dist/ build/

      - name: Create WindGIS GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: WindGIS Release ${{ needs.windgis-prepare.outputs.version }}
          body: |
            WindGIS version of Mapbox GL JS - Release ${{ needs.windgis-prepare.outputs.version }}

            This is a custom build for WindGIS organization.
          draft: false
          prerelease: false

      - name: Upload WindGIS release assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windgis-package-${{ needs.windgis-prepare.outputs.version }}.tar.gz
          asset_name: windgis-package-${{ needs.windgis-prepare.outputs.version }}.tar.gz
          asset_content_type: application/gzip
